spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:applicationdb
    username: sa
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    format-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 5242880
      max-request-size: 5242880

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        #web-admin-password: password
server:
  port: 8081
springdoc:
  api-docs:
    path: /api/
  swagger-ui:
    path: /swagger-ui

signature:
  image:
    location: /Users/abhibhowmick/Documents
    type: jpg,jpeg,png,gif

logging:
  level:
    org:
      springframework:
        web: INFO
        boot:
          autoconfigure:
            web:
              servlet: DEBUG
      hibernate:
        type: INFO