spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:applicationdb
    username: sa
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    format-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        #web-admin-password: password
server:
  port: 8081
springdoc:
  api-docs:
    path: /api/
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate:
        type: INFO